FROM node:22.17.0-alpine

RUN apk add --no-cache libc6-compat

WORKDIR /app

COPY package.json package-lock.json* ./

RUN npm install --legacy-peer-deps

COPY . .

EXPOSE 3001

ENV PORT 3001
ENV HOSTNAME 0.0.0.0
ENV NODE_ENV development

CMD ["npm", "run", "dev"]

